### ISSUE TITLE
Move & export custom types

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.React#18]
The custom types declared for the [service-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/src/services/service-factory.ts) and [service-hook-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/src/services/service-hook-factory.ts) were declared in the same files as the implementation that used them, but would probably make more sense to be broken out into a `types` folder with a consistent naming structure:

`BulkUpdateService` from [service-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/src/services/service-factory.ts) -> `types/bulk-update-service-type.ts`
`CreateService` from [service-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/src/services/service-factory.ts) -> `types/create-service-type.ts`
...
`BulkUpdateServiceHook` from [service-hook-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/src/services/service-hook-factory.ts) -> `types/bulk-update-service-hook-type.ts` and so on.

Make sure these are exported from `index.ts` for consumer use.

**Comment by wintondeshong** [comment]
👍

**Comment by brandongregoryscott** [comment]
I've got some time this afternoon, should be able to get this out quick 👍
