### ISSUE TITLE
Refactor into Core package - Enums, interfaces, records, utilities

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.React#2]
The following interfaces, records, and their associated tests should be pulled into the [AndcultureCode.JavaScript.Core](https://github.com/AndcultureCode/AndcultureCode.JavaScript.Core) package, since they are not React-specific data structures or concepts.

[enumerations/error-type.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/enumerations/error-type.ts)
[interfaces/paged-result.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/interfaces/paged-result.ts)
[interfaces/result-error.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/interfaces/result-error.ts)
[interfaces/result.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/interfaces/result.ts)
[interfaces/service-response.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/interfaces/service-response.ts)
[view-models/result-error-record.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/view-models/result-error-record.ts)
[view-models/result-record.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/view-models/result-record.ts)

Be sure to revisit tests and ensure there is reasonable test coverage where it makes sense.

If it makes sense or is necessary, pull these utility classes into the core package as well:
[utilities/collection-utils.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/utilities/collection-utils.ts)
[utilities/core-utils.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/utilities/core-utils.ts)

**Comment by brandongregoryscott** [comment]
@wintondeshong Feel free to add additional files that should be ported over into Core. I'm not sure how many non-React projects we have/will have in the near future, but I could see [services/service-factory.ts](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/tree/master/src/services/service-factory.ts) being ported over as well since there is no dependency on React there.

**Comment by wintondeshong** [comment]
Going to be tackling this today

**Comment by wintondeshong** [comment]
Published in version v0.0.2
