### ISSUE TITLE
Declaration files do not retain JSDoc comments

### ISSUE THREAD

**Issue by myty** [AndcultureCode/AndcultureCode.JavaScript.React#37]
After publish, the JSDoc comments are not retained in neither the typescript declaration files or transpiled javascript.  The reason being this line:
https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/c5d923dc395e1fcc1943ac12f91e03f5194bc9a7/tsconfig.json#L18

This is a known issue, but there still isn't a solution that allows for removing comments but still keeping the JSDoc comments. See here: https://github.com/Microsoft/TypeScript/issues/14619  

The simplest solution for the time being is to set `"removeComments": false`

**Comment by myty** [comment]
@wintondeshong @brandongregoryscott What are your thoughts on not removing comments?  Having the JSDoc comments would make a much better development experience when consuming and using this as a package.

**Comment by brandongregoryscott** [comment]
Good catch! Probably just an oversight on our part when originally setting up the package. I think we can safely flip that setting to false, there shouldn't be any sensitive information in the comments that wouldn't already be exposed through the source code anyway.
