### ISSUE TITLE
Docs links should point back to the andculture repo

### ISSUE THREAD

**Issue by myty** [AndcultureCode/AndcultureCode.JavaScript.React#4]
Links in the docs section that are a pointer back to a specific line of code should link to the andculture repo.  

The links, for example, look something like this:

> Defined in src/interfaces/authenticated-route.ts:12

As an example file: https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/blob/master/docs/interfaces/authenticatedroute.md

Currently, the links point to the source of the PR merge

**Comment by wintondeshong** [comment]
Yeah, the docs get re-generated when a new published version goes out so we kinda let it slide. I've re-generated the docs and pushed so it is corrected. If this resolved it go ahead and close 👍
