### ISSUE TITLE
Port over `useQuery` custom hook

### ISSUE THREAD

**Issue by mrjones2014** [AndcultureCode/AndcultureCode.JavaScript.React#40]
`useQuery` from client project. 

Basically takes a record type and a params interface type as generic type arguments, re-runs the query and returns results whenever the query changes.

**Comment by brandongregoryscott** [comment]
Published with [v0.2.0](https://github.com/AndcultureCode/AndcultureCode.JavaScript.React/releases/tag/v0.2.0)
